package com.susie.ierp.mybatis;

import java.util.Date;

public class Bill {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bill.id
	 * @mbg.generated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bill.bill_no
	 * @mbg.generated
	 */
	private String billNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bill.bill_mny
	 * @mbg.generated
	 */
	private String billMny;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bill.pay_type
	 * @mbg.generated
	 */
	private String payType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bill.salesman
	 * @mbg.generated
	 */
	private String salesman;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bill.ts
	 * @mbg.generated
	 */
	private Date ts;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bill.id
	 * @return  the value of bill.id
	 * @mbg.generated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bill.id
	 * @param id  the value for bill.id
	 * @mbg.generated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bill.bill_no
	 * @return  the value of bill.bill_no
	 * @mbg.generated
	 */
	public String getBillNo() {
		return billNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bill.bill_no
	 * @param billNo  the value for bill.bill_no
	 * @mbg.generated
	 */
	public void setBillNo(String billNo) {
		this.billNo = billNo == null ? null : billNo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bill.bill_mny
	 * @return  the value of bill.bill_mny
	 * @mbg.generated
	 */
	public String getBillMny() {
		return billMny;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bill.bill_mny
	 * @param billMny  the value for bill.bill_mny
	 * @mbg.generated
	 */
	public void setBillMny(String billMny) {
		this.billMny = billMny == null ? null : billMny.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bill.pay_type
	 * @return  the value of bill.pay_type
	 * @mbg.generated
	 */
	public String getPayType() {
		return payType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bill.pay_type
	 * @param payType  the value for bill.pay_type
	 * @mbg.generated
	 */
	public void setPayType(String payType) {
		this.payType = payType == null ? null : payType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bill.salesman
	 * @return  the value of bill.salesman
	 * @mbg.generated
	 */
	public String getSalesman() {
		return salesman;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bill.salesman
	 * @param salesman  the value for bill.salesman
	 * @mbg.generated
	 */
	public void setSalesman(String salesman) {
		this.salesman = salesman == null ? null : salesman.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bill.ts
	 * @return  the value of bill.ts
	 * @mbg.generated
	 */
	public Date getTs() {
		return ts;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bill.ts
	 * @param ts  the value for bill.ts
	 * @mbg.generated
	 */
	public void setTs(Date ts) {
		this.ts = ts;
	}
}