package com.susie.ierp.mybatis;

import java.util.List;

import org.apache.ibatis.annotations.Param;

//@MapperScan
//@Resource
public interface BillMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bill
	 * @mbg.generated
	 */
	long countByExample(BillExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bill
	 * @mbg.generated
	 */
	int deleteByExample(BillExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bill
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bill
	 * @mbg.generated
	 */
	int insert(Bill record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bill
	 * @mbg.generated
	 */
	int insertSelective(Bill record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bill
	 * @mbg.generated
	 */
	List<Bill> selectByExample(BillExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bill
	 * @mbg.generated
	 */
	Bill selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bill
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("record") Bill record, @Param("example") BillExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bill
	 * @mbg.generated
	 */
	int updateByExample(@Param("record") Bill record, @Param("example") BillExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bill
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(Bill record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bill
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Bill record);
}